# **<center><span style= "color:#2F539B;">All About Numpy</span></center>**

## ***<span style= "color:maroon;">Content </span>***
- ***`Imports`*** 
- **`Multidimensional arrays`** 
- **`Slicing`**
- **`Arithmetic function`**
- **`Numpy Broadcasting`**
- **`Aggregate functions`**
- **`Filtering in Numpy`**
- **`Random numbers in Numpy`**

## ***<span style= "color:purple;">Imports </span>***

In [ ]:
import numpy as np

## ***<span style= "color:#EE9A4D;">Multidimensional arrays </span>***

In [2]:
# Creating a 1D array
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.size)
print(arr.shape)

[10 20 30 40 50]
<class 'numpy.ndarray'>
1
5
(5,)


In [3]:
#Accessing in 1D array
print(arr[0])
print(arr[1])

10
20


In [4]:
# Creating a 2D array
arr2D = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr2D)
print(type(arr2D))
print(arr2D.ndim)
print(arr2D.size)
print(arr2D.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
<class 'numpy.ndarray'>
2
9
(3, 3)


In [5]:
#Accessing 2D array
# Row x Column
print(arr2D[1,2]) # Accessing element at 2nd row and 3rd column
print(arr2D[2,0])

60
70


In [8]:
# Creating a 3D array
# A 3D array = multiple 2D arrays (row X columns) stacked together

arr3D = np.array([[[10,20,30],
                   [40,50,60],
                   [70,80,90]],

                  [[100,110,120],
                   [130,140,150],
                   [160,170,180]],

                   [[190,200,210],
                    [220,230,240],
                    [250,260,270]]])
# 3 blocks, each block has 3 rows and 3 columns
print(arr3D)

[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 110 120]
  [130 140 150]
  [160 170 180]]

 [[190 200 210]
  [220 230 240]
  [250 260 270]]]


In [12]:
# Accessing 3D array
# Block x Row X Column
print(arr3D[0,1,1])
print(arr3D[2,2,1])

50
260


In [13]:
print(arr3D.ndim)
print(arr3D.size)
print(arr3D.shape)

3
27
(3, 3, 3)


## ***<span style= "color:#EE9A4D;">Slicing in Numpy </span>***

In [21]:
# Creating 1D array for slicing
sliceArr = np.array([10,20,30,40,50,60,70,80])
print(sliceArr)

[10 20 30 40 50 60 70 80]


In [24]:
# Accessing 1D array using slicing
# arr[starting index: ending index: step]
# starting index is inclusive, ending index is exclusive
print(sliceArr[1:2])
print(sliceArr[1:5:2])

[20]
[20 40]


In [25]:
# Creating 2D array for slicing
sliceArr2D = np.array( [[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12],
                        [13,14,15,16]])
print(sliceArr2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# Aaccessing 2D array using slicing

# arr[starting index: ending index: step]
# starting index is inclusive, ending index is exclusive
# Just rows
print(sliceArr2D[0])
print(sliceArr2D[1:3])

# Just columns
print(sliceArr2D[:,0])

# arr[row_start:row_end, col_start:col_end: step] 
# starting index is inclusive, ending index is exclusive
# Rows and columns
print(sliceArr2D[1:3, 1:3])

[1 2 3 4]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  5  9 13]
[[ 6  7]
 [10 11]]


In [35]:
# Creating 3D array for slicing
sliceArr3D = np.array([[[10,20,30],
                        [40,50,60],
                        [70,80,90]],

                        [[100,110,120],
                         [130,140,150],
                         [160,170,180]],
                         
                        [[190,200,210],
                         [220,230,240],
                         [250,260,270]]])
print(sliceArr3D)

[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 110 120]
  [130 140 150]
  [160 170 180]]

 [[190 200 210]
  [220 230 240]
  [250 260 270]]]


In [ ]:
# Accessing 3D array
# Block x Row x Column

print(sliceArr3D[1, 1:,0:2 ])

[[130 140]
 [160 170]]


## ***<span style= "color:#EE9A4D;">Arithmetic functions </span>***

In [42]:
aritharr = np.array([1,2,3])

In [ ]:
# Scalar operations
print(aritharr + 5)
print(aritharr * 3)
print(aritharr ** 3)

[6 7 8]
[3 6 9]
[ 1  8 27]


In [47]:
# Vectorized functions
print(np.sqrt(aritharr))
print(np.round(aritharr))

[1.         1.41421356 1.73205081]
[1 2 3]


## ***<span style= "color:#EE9A4D;">Broadcasting in Numpy </span>***

#### Broadcasting allows Numpy to perform operations on arrays with different shapes virtually expanding dimensions so they match the larger array's shape.
### Asumptions are

#### The dimensions have the same size or One of the dimensions has a size of 1.
#### arr1(4x3) + arr2(1x3) = result(4x3)

In [50]:
arr1 = np.array([[1,2,3,4]])
arr2 = np.array([[1],[2],[3],[4]])
#Both arrays have different shapes but have size of 1. So they can be broadcasted.
print(arr1.shape)
print(arr2.shape)

(1, 4)
(4, 1)


In [52]:
# Broadcasting
print(arr1*arr2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


## ***<span style= "color:#EE9A4D;">Aggregate fucntion </span>***

In [53]:
aggarr = np.array([[1,2,3,4,5],
                   [6,7,8,9,10]])

print(aggarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [60]:
# Aggregate functions
print(np.sum(aggarr))
# Central tendency measures
print(np.mean(aggarr))
print(np.median(aggarr))

# Dispersion measures
print(np.min(aggarr))
print(np.max(aggarr))
print(np.argmin(aggarr))
print(np.var(aggarr))
print(np.std(aggarr))


55
5.5
5.5
1
10
0
8.25
2.8722813232690143


## ***<span style= "color:#EE9A4D;">Filtering in Numpy </span>***

In [72]:
ageArr = np.array([[21,17,19,20,16,30,18,65],
                   [39,22,15,99,18,19,20,21]])
teenagers = ageArr[ageArr < 18].copy()
print(teenagers)
adults = ageArr[(ageArr > 18) & (ageArr < 65)].copy()

print(adults)


[17 16 15]
[21 19 20 30 39 22 19 20 21]


## ***<span style= "color:#EE9A4D;">Random numbers in Numpy </span>***

In [ ]:
rng = np.random.default_rng()

In [74]:
print(rng.integers(0,50, size=(3,4)))

[[32 31 17 44]
 [35 43 17 47]
 [40 30 35 49]]
